    create table endereco (
       id integer generated by default as identity,
       tipoEndereco varchar(50),
       tipoLogradouro varchar(50),
       logradouro varchar(255),
       numero varchar(6),
       complemento varchar(255),
       bairro varchar(100),
       cidade varchar(100),
       estado varchar(100),
       pais varchar(100),
       primary key (id)
    )