    create table telefone (
       id integer generated by default as identity,
       tipoTelefone integer,
       ddi varchar(5),
       ddd varchar(5) not null,
       telefone varchar(10),
       primary key (id)
    )
