create table agenda (
     id integer generated by default as identity,
     data_cadastro timestamp,
     deletado boolean not null,
     nome varchar(255),
     sobrenome varchar(255),
     apelido varchar(255),
     dtNascimento varchar(255),
     enderecos_id integer,
     telefones_id integer,
     email_id integer,
     primary key (id)
);

alter table agenda 
   add constraint fk_agenda_Endereco
   foreign key (enderecos_id)
   references endereco;


alter table agenda 
   add constraint fk_agenda_telefone
   foreign key (telefones_id) 
   references telefone;
   
alter table agenda 
   add constraint fk_agenda_email
   foreign key (email_id) 
   references email;
